
management:
  endpoints:
    web:
      exposure:
        include: '*'
  
server:
  port: 8080
  
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/KDGames?createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    open-in-view: false
  thymeleaf: # Thymeleaf
    cache: false
    mode: CSS
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0
    
logging:
  level:
    root: INFO
    com.cadykd.kdgames: INFO
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql: INFO

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=